const fontFamily = {
  light: 'Inter-Light',
  regular: 'Inter-Regular',
  medium: 'Inter-Medium',
  bold: 'Inter-Bold',
  black: 'Inter-Black',
};

export const Typography = {
  headline: {
    fontFamily: fontFamily.light,
    fontSize: 32,
    fontWeight: '300',
    lineHeight: 40,
    letterSpacing: 0.2,
  },
  subHeadline: {
    fontFamily: fontFamily.regular,
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 28,
    letterSpacing: 0.1,
  },
  paragraph: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: 0.05,
  },
  light: {
    small: {
      fontFamily: fontFamily.light,
      fontSize: 12,
      fontWeight: '300',
      lineHeight: 16,
      letterSpacing: 0.05,
    },
    medium: {
      fontFamily: fontFamily.light,
      fontSize: 16,
      fontWeight: '300',
      lineHeight: 24,
      letterSpacing: 0.05,
    },
    large: {
      fontFamily: fontFamily.light,
      fontSize: 20,
      fontWeight: '300',
      lineHeight: 28,
      letterSpacing: 0.1,
    },
  },
  regular: {
    small: {
      fontFamily: fontFamily.regular,
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
      letterSpacing: 0.05,
    },
    medium: {
      fontFamily: fontFamily.regular,
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
      letterSpacing: 0.05,
    },
    large: {
      fontFamily: fontFamily.regular,
      fontSize: 20,
      fontWeight: '400',
      lineHeight: 28,
      letterSpacing: 0.1,
    },
  },
  medium: {
    small: {
      fontFamily: fontFamily.medium,
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
      letterSpacing: 0.05,
    },
    medium: {
      fontFamily: fontFamily.medium,
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 24,
      letterSpacing: 0.05,
    },
    large: {
      fontFamily: fontFamily.medium,
      fontSize: 20,
      fontWeight: '500',
      lineHeight: 28,
      letterSpacing: 0.1,
    },
  },
  bold: {
    small: {
      fontFamily: fontFamily.bold,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
      letterSpacing: 0.05,
    },
    medium: {
      fontFamily: fontFamily.bold,
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 24,
      letterSpacing: 0.05,
    },
    large: {
      fontFamily: fontFamily.bold,
      fontSize: 20,
      fontWeight: '700',
      lineHeight: 28,
      letterSpacing: 0.1,
    },
  },
  black: {
    small: {
      fontFamily: fontFamily.black,
      fontSize: 12,
      fontWeight: '900',
      lineHeight: 16,
      letterSpacing: 0.05,
    },
    medium: {
      fontFamily: fontFamily.black,
      fontSize: 16,
      fontWeight: '900',
      lineHeight: 24,
      letterSpacing: 0.05,
    },
    large: {
      fontFamily: fontFamily.black,
      fontSize: 20,
      fontWeight: '900',
      lineHeight: 28,
      letterSpacing: 0.1,
    },
  },
};
