import type { GetSwapResponse } from '@lendasat/lendaswap-sdk-pure';
import type { StoredSwap, SwapStorage, WalletStorage } from '@lendasat/lendaswap-sdk-pure';

import { IStorage, STORAGE_KEY_SATORA_SWAPS, STORAGE_KEY_SATORA_WALLET } from '../types/IStorage';

interface PersistedWallet {
  mnemonic: string | null;
  keyIndex: number;
}

const EMPTY_WALLET: PersistedWallet = { mnemonic: null, keyIndex: 0 };

/**
 * Backs the Satora SDK's WalletStorage with our IStorage. The mnemonic stored here
 * is a Satora-only seed generated by the SDK on first build — it is independent
 * from the user's main wallet seed. Only used to derive ephemeral EVM keys for
 * gasless Permit2 signing of Satora swaps.
 *
 * TODO: derive the Satora signer from the wallet master seed instead. Once that's
 * done, getMnemonic() returns a derived value and there's nothing to persist —
 * SecureStorage becomes unnecessary.
 */
export class SatoraWalletStorageAdapter implements WalletStorage {
  constructor(private readonly storage: IStorage) {}

  private async load(): Promise<PersistedWallet> {
    const raw = await this.storage.getItem(STORAGE_KEY_SATORA_WALLET);
    if (!raw) return { ...EMPTY_WALLET };
    try {
      const parsed = JSON.parse(raw) as Partial<PersistedWallet>;
      return {
        mnemonic: typeof parsed.mnemonic === 'string' ? parsed.mnemonic : null,
        keyIndex: typeof parsed.keyIndex === 'number' ? parsed.keyIndex : 0,
      };
    } catch {
      return { ...EMPTY_WALLET };
    }
  }

  private async save(value: PersistedWallet): Promise<void> {
    await this.storage.setItem(STORAGE_KEY_SATORA_WALLET, JSON.stringify(value));
  }

  async getMnemonic(): Promise<string | null> {
    return (await this.load()).mnemonic;
  }

  async setMnemonic(mnemonic: string): Promise<void> {
    const current = await this.load();
    await this.save({ ...current, mnemonic });
  }

  async getKeyIndex(): Promise<number> {
    return (await this.load()).keyIndex;
  }

  async setKeyIndex(index: number): Promise<void> {
    const current = await this.load();
    await this.save({ ...current, keyIndex: index });
  }

  async incrementKeyIndex(): Promise<number> {
    const current = await this.load();
    const used = current.keyIndex;
    await this.save({ ...current, keyIndex: used + 1 });
    return used;
  }

  async clear(): Promise<void> {
    await this.save({ ...EMPTY_WALLET });
  }
}

/** Backs the Satora SDK's SwapStorage with a JSON blob in IStorage. */
export class SatoraSwapStorageAdapter implements SwapStorage {
  constructor(private readonly storage: IStorage) {}

  private async loadAll(): Promise<Record<string, StoredSwap>> {
    const raw = await this.storage.getItem(STORAGE_KEY_SATORA_SWAPS);
    if (!raw) return {};
    try {
      const parsed = JSON.parse(raw);
      return parsed && typeof parsed === 'object' ? (parsed as Record<string, StoredSwap>) : {};
    } catch {
      return {};
    }
  }

  private async saveAll(map: Record<string, StoredSwap>): Promise<void> {
    await this.storage.setItem(STORAGE_KEY_SATORA_SWAPS, JSON.stringify(map));
  }

  async get(swapId: string): Promise<StoredSwap | null> {
    const all = await this.loadAll();
    return all[swapId] ?? null;
  }

  async store(swap: StoredSwap): Promise<void> {
    const all = await this.loadAll();
    all[swap.swapId] = swap;
    await this.saveAll(all);
  }

  async update(swapId: string, response: GetSwapResponse): Promise<void> {
    const all = await this.loadAll();
    const existing = all[swapId];
    if (!existing) {
      throw new Error(`Satora swap not found: ${swapId}`);
    }
    all[swapId] = { ...existing, response, updatedAt: Date.now() };
    await this.saveAll(all);
  }

  async delete(swapId: string): Promise<void> {
    const all = await this.loadAll();
    delete all[swapId];
    await this.saveAll(all);
  }

  async list(): Promise<string[]> {
    return Object.keys(await this.loadAll());
  }

  async getAll(): Promise<StoredSwap[]> {
    return Object.values(await this.loadAll());
  }

  async clear(): Promise<void> {
    await this.saveAll({});
  }
}
