export const STORAGE_KEY_MNEMONIC = 'STORAGE_KEY_MNEMONIC';
export const ENCRYPTED_PREFIX = 'encrypted://';
export const STORAGE_KEY_BTC_XPUB = 'STORAGE_KEY_BTC_XPUB';
export const STORAGE_KEY_EVM_XPUB = 'STORAGE_KEY_EVM_XPUB';
export const STORAGE_KEY_WHITELIST = 'STORAGE_KEY_WHITELIST';
export const STORAGE_KEY_ACCEPTED_TOS = 'STORAGE_KEY_ACCEPTED_TOS';
export const STORAGE_KEY_SERIALIZED = 'STORAGE_KEY_SERIALIZED';
export const STORAGE_KEY_SETTINGS = 'STORAGE_KEY_SETTINGS';
export const STORAGE_KEY_SEED_VERIFIED = 'STORAGE_KEY_SEED_VERIFIED';
export const STORAGE_KEY_SIDESHIFT_TRANSFERS = 'STORAGE_KEY_SIDESHIFT_TRANSFERS';
export const STORAGE_KEY_NATIVE_DEPOSIT_TRANSFERS = 'STORAGE_KEY_NATIVE_DEPOSIT_TRANSFERS';
export const STORAGE_KEY_GARDEN_TRANSFERS = 'STORAGE_KEY_GARDEN_TRANSFERS';
export const STORAGE_KEY_SYMBIOSIS_TRANSFERS = 'STORAGE_KEY_SYMBIOSIS_TRANSFERS';
export const STORAGE_KEY_FLASHNET_TRANSFERS = 'STORAGE_KEY_FLASHNET_TRANSFERS';
export const STORAGE_KEY_SPARK_REFUNDED_DEPOSITS = 'STORAGE_KEY_SPARK_REFUNDED_DEPOSITS';
export const STORAGE_KEY_SATORA_WALLET = 'STORAGE_KEY_SATORA_WALLET';
export const STORAGE_KEY_SATORA_SWAPS = 'STORAGE_KEY_SATORA_SWAPS';

export interface IStorage {
  setItem(key: string, value: string): Promise<void>;
  getItem(key: string): Promise<string>;
}

export const getSerializedStorageKey = (network: string, accountNumber: number) => {
  return `${STORAGE_KEY_SERIALIZED}_${network}_${accountNumber}`;
};
