import { NetworkInfo } from '../types/network-info';
import {
  NETWORK_ARK_MUTINYNET,
  NETWORK_ARK,
  NETWORK_BITCOIN,
  NETWORK_LIQUID,
  NETWORK_LIQUID_TESTNET,
  NETWORK_CITREA_TESTNET,
  NETWORK_ROOTSTOCK,
  NETWORK_SEPOLIA,
  NETWORK_SPARK,
  NETWORK_ALPEN_TESTNET,
  NETWORK_LIGHTNING,
  NETWORK_LIGHTNING_TESTNET,
  Networks,
  NETWORK_USDT,
  NETWORK_STACKS,
  NETWORK_CITREA,
} from '../types/networks';

export const AllNetworkInfos: Record<Networks, NetworkInfo> = {
  [NETWORK_BITCOIN]: {
    chainId: 0,
    displayName: 'Bitcoin',
    ticker: 'BTC',
    decimals: 8,
    explorerUrl: 'https://layerz.mempool.space',
    rpcUrl: '',
    isEVM: false,
    sortIndex: 0,
  },
  [NETWORK_ROOTSTOCK]: {
    chainId: 30,
    displayName: 'Rootstock',
    ticker: 'RBTC',
    rpcUrl: 'https://rpc.mainnet.rootstock.io/rFOXXhwHGfZbgbVVVbNvpyVdr4VjE6-M',
    explorerUrl: 'https://rootstock.blockscout.com',
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/rootstock',
    decimals: 18,
    isEVM: true,
    etherScanApiUrl: 'https://rootstock.blockscout.com/api',
    sortIndex: 60,
  },
  [NETWORK_ALPEN_TESTNET]: {
    chainId: 2892,
    displayName: 'Alpen Testnet',
    ticker: 'sBTC',
    rpcUrl: 'https://rpc.testnet.alpenlabs.io',
    explorerUrl: 'https://explorer.testnet.alpenlabs.io',
    decimals: 18,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/alpen',
    isTestnet: true,
    isEVM: true,
    etherScanApiUrl: 'https://explorer.testnet.alpenlabs.io/api',
    sortIndex: 110,
  },
  [NETWORK_SEPOLIA]: {
    chainId: 11155111,
    displayName: 'Sepolia',
    ticker: 'SepoliaETH',
    rpcUrl: 'https://sepolia.infura.io/v3/875fcd83840448e489608311502ae61c',
    explorerUrl: 'https://sepolia.etherscan.io',
    decimals: 18,
    isTestnet: true,
    isEVM: true,
    etherScanApiUrl: 'https://api-sepolia.etherscan.io/api',
    sortIndex: 1,
  },

  [NETWORK_CITREA]: {
    chainId: 4114,
    displayName: 'Citrea',
    ticker: 'cBTC',
    rpcUrl: 'https://rpc.mainnet.citrea.xyz',
    explorerUrl: 'https://explorer.mainnet.citrea.xyz',
    decimals: 18,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/citrea',
    isTestnet: false,
    isEVM: true,
    etherScanApiUrl: 'https://explorer.mainnet.citrea.xyz/api',
    sortIndex: 14,
  },
  [NETWORK_CITREA_TESTNET]: {
    chainId: 5115,
    displayName: 'Citrea Testnet',
    ticker: 'cBTC',
    rpcUrl: 'https://rpc.testnet.citrea.xyz',
    explorerUrl: 'https://explorer.testnet.citrea.xyz',
    decimals: 18,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/citrea',
    isTestnet: true,
    isEVM: true,
    etherScanApiUrl: 'https://explorer.testnet.citrea.xyz/api',
    sortIndex: 90,
  },
  [NETWORK_ARK_MUTINYNET]: {
    chainId: -1,
    displayName: 'ARK Mutinynet',
    ticker: 'BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://arklabs.to/',
    isTestnet: true,
    isEVM: false,
    sortIndex: 30,
  },
  [NETWORK_ARK]: {
    chainId: -1,
    displayName: 'ARK',
    ticker: 'BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://arklabs.to/',
    isTestnet: false,
    isEVM: false,
    sortIndex: 15,
  },
  [NETWORK_LIQUID]: {
    chainId: 11,
    displayName: 'Liquid',
    ticker: 'L-BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/liquid',
    isEVM: false,
    sortIndex: 20,
  },
  [NETWORK_LIQUID_TESTNET]: {
    chainId: 12,
    displayName: 'Liquid Testnet',
    ticker: 'tL-BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/liquid',
    isTestnet: true,
    isEVM: false,
    sortIndex: 80,
  },
  [NETWORK_SPARK]: {
    chainId: 13,
    displayName: 'Spark',
    ticker: 'BTC',
    rpcUrl: '',
    explorerUrl: 'https://sparkscan.io',
    decimals: 8,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/spark',
    isTestnet: false,
    isEVM: false,
    sortIndex: 40,
  },
  [NETWORK_LIGHTNING]: {
    chainId: 14,
    displayName: 'Lightning',
    ticker: 'BTC',
    decimals: 8,
    explorerUrl: 'https://layerz.mempool.space/lightning',
    rpcUrl: '',
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/lightning',
    isEVM: false,
    sortIndex: 10,
  },
  [NETWORK_LIGHTNING_TESTNET]: {
    chainId: 15,
    displayName: 'Lightning Testnet',
    ticker: 'tBTC',
    decimals: 8,
    explorerUrl: 'https://mempool.space/testnet/lightning',
    rpcUrl: '',
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/lightning',
    isTestnet: true,
    isEVM: false,
    sortIndex: 70,
  },
  [NETWORK_USDT]: {
    chainId: 16,
    displayName: 'USDT',
    ticker: 'USDT',
    decimals: 0, // because it is a meta network that consists of several tokens with different decimals we apply decimal rules on a per token basis
    explorerUrl: '',
    rpcUrl: '',
    knowMoreUrl: 'https://tether.to',
    isEVM: false,
    sortIndex: 12,
  },
  [NETWORK_STACKS]: {
    chainId: 17,
    displayName: 'Stacks',
    ticker: 'sBTC',
    decimals: 8,
    explorerUrl: 'https://explorer.hiro.so/',
    rpcUrl: '',
    knowMoreUrl: 'https://stacks.org',
    isEVM: false,
    sortIndex: 70,
  },
};
