import { NetworkInfo } from '../types/network-info';
import {
  NETWORK_ARK_MUTINYNET,
  NETWORK_BITCOIN,
  NETWORK_BOTANIX_TESTNET,
  NETWORK_LIQUID,
  NETWORK_LIQUID_TESTNET,
  NETWORK_CITREA_TESTNET,
  NETWORK_ROOTSTOCK,
  NETWORK_SEPOLIA,
  NETWORK_SPARK,
  NETWORK_ALPEN_TESTNET,
  NETWORK_LIGHTNING,
  NETWORK_LIGHTNING_TESTNET,
  Networks,
  NETWORK_BOTANIX,
} from '../types/networks';

export const AllNetworkInfos: Record<Networks, NetworkInfo> = {
  [NETWORK_BITCOIN]: {
    chainId: 0,
    ticker: 'BTC',
    decimals: 8,
    explorerUrl: 'https://mempool.space',
    rpcUrl: '',
    isEVM: false,
  },
  [NETWORK_ROOTSTOCK]: {
    chainId: 30,
    ticker: 'RBTC',
    rpcUrl: 'https://rpc.mainnet.rootstock.io/rFOXXhwHGfZbgbVVVbNvpyVdr4VjE6-M',
    explorerUrl: 'https://rootstock.blockscout.com',
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/rootstock',
    decimals: 18,
    isEVM: true,
  },
  [NETWORK_BOTANIX_TESTNET]: {
    chainId: 3636,
    ticker: 'BTC',
    rpcUrl: 'https://node.botanixlabs.dev',
    explorerUrl: 'https://testnet.botanixscan.io',
    decimals: 18,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/botanix',
    isTestnet: true,
    isEVM: true,
  },
  [NETWORK_BOTANIX]: {
    chainId: 3637,
    ticker: 'BTC',
    rpcUrl: 'https://rpc.botanixlabs.com',
    explorerUrl: 'https://botanixscan.io',
    decimals: 18,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/botanix',
    isTestnet: false,
    isEVM: true,
  },
  [NETWORK_ALPEN_TESTNET]: {
    chainId: 2892,
    ticker: 'sBTC',
    rpcUrl: 'https://rpc.testnet.alpenlabs.io',
    explorerUrl: 'https://explorer.testnet.alpenlabs.io',
    decimals: 18,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/strata',
    isTestnet: true,
    isEVM: true,
  },
  [NETWORK_SEPOLIA]: {
    chainId: 11155111,
    ticker: 'SepoliaETH',
    rpcUrl: 'https://sepolia.infura.io/v3/875fcd83840448e489608311502ae61c',
    explorerUrl: 'https://sepolia.etherscan.io',
    decimals: 18,
    isTestnet: true,
    isEVM: true,
  },
  [NETWORK_CITREA_TESTNET]: {
    chainId: 5115,
    ticker: 'cBTC',
    rpcUrl: 'https://rpc.testnet.citrea.xyz',
    explorerUrl: 'https://explorer.testnet.citrea.xyz',
    decimals: 18,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/citrea',
    isTestnet: true,
    isEVM: true,
  },
  [NETWORK_ARK_MUTINYNET]: {
    chainId: -1,
    ticker: 'BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://arklabs.to/',
    isTestnet: true,
    isEVM: false,
  },
  [NETWORK_LIQUID]: {
    chainId: 11,
    ticker: 'L-BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/liquid',
    isEVM: false,
  },
  [NETWORK_LIQUID_TESTNET]: {
    chainId: 12,
    ticker: 'tL-BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/liquid',
    isTestnet: true,
    isEVM: false,
  },
  [NETWORK_SPARK]: {
    chainId: 13,
    ticker: 'BTC',
    rpcUrl: '',
    explorerUrl: '',
    decimals: 8,
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/spark',
    isTestnet: false,
    isEVM: false,
  },
  [NETWORK_LIGHTNING]: {
    chainId: 14,
    ticker: 'BTC',
    decimals: 8,
    explorerUrl: 'https://mempool.space/lightning',
    rpcUrl: '',
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/lightning',
    isEVM: false,
  },
  [NETWORK_LIGHTNING_TESTNET]: {
    chainId: 15,
    ticker: 'tBTC',
    decimals: 8,
    explorerUrl: 'https://mempool.space/testnet/lightning',
    rpcUrl: '',
    knowMoreUrl: 'https://www.bitcoinlayers.org/layers/lightning',
    isTestnet: true,
    isEVM: false,
  },
};
