import { Networks, NETWORK_BITCOIN, NETWORK_CITREA_TESTNET, NETWORK_BOTANIX, NETWORK_ROOTSTOCK, NETWORK_CITREA, NETWORK_LIGHTNING, NETWORK_SPARK, NETWORK_ARK } from '../types/networks';
import { PartnerInfo } from '../types/partner-info';

const partnersList: PartnerInfo[] = [
  {
    name: 'BTC Map',
    network: NETWORK_BITCOIN,
    url: 'https://btcmap.org/map',
    imgUrl: 'https://cdn.brandfetch.io/idUWkC2cvG/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1759867429752',
    highlight: 'https://btcmap.org/images/og/map.png',
    description: 'Find places to spend sats wherever you are',
  },
  {
    name: 'AirBTC',
    network: NETWORK_BITCOIN,
    url: 'https://airbtc.online',
    imgUrl: 'https://cdn.brandfetch.io/id5Cbx0-cD/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1757511823062',
    description: 'Stay anywhere with Bitcoin',
  },
  {
    name: 'Boltz',
    network: NETWORK_BITCOIN,
    url: 'https://boltz.exchange/',
    imgUrl: 'https://cdn.brandfetch.io/ido147kV5m/w/390/h/390/theme/dark/icon.png?c=1bxid64Mup7aczewSAYMX&t=1760962230818',
    highlight: 'https://cdn.brandfetch.io/ido147kV5m/w/390/h/390/theme/dark/icon.png?c=1bxid64Mup7aczewSAYMX&t=1760962230818',
    description: 'Non-custodial Bitcoin bridge',
  },
  {
    name: 'Stacker News',
    network: NETWORK_LIGHTNING,
    url: 'https://stacker.news/',
    imgUrl: 'https://cdn.brandfetch.io/id1b_CmEE6/w/256/h/256/theme/dark/icon.png?c=1bxid64Mup7aczewSAYMX&t=1764689848903',
    description: 'Upvote and comment on the latest news in the Bitcoin ecosystem',
  },
  {
    name: 'Satlantis',
    network: NETWORK_LIGHTNING,
    url: 'https://www.satlantis.io/events',
    imgUrl: 'https://cdn.brandfetch.io/id09y2K0BQ/w/180/h/180/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1745426752134',
    description: 'Curated places and real-world experiences powered by Bitcoin.',
  },
  {
    name: 'BitcoinFlash',
    network: NETWORK_LIGHTNING,
    url: 'https://bitcoinflash.xyz/',
    imgUrl: 'https://cdn.brandfetch.io/idXI0XZ_Sl/w/180/h/180/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1772219346444',
    description: 'Access Bitcoin with low-friction options.',
  },
  {
    name: 'Bit.Spenda',
    network: NETWORK_LIGHTNING,
    url: 'https://send.bitspenda.app',
    imgUrl: 'https://send.bitspenda.app/logo.png',
    description: 'Spend Bitcoin via gift cards and spend-ready flows.',
  },
  {
    name: 'BitZed',
    network: NETWORK_LIGHTNING,
    url: 'https://app.bitzed.xyz',
    imgUrl: 'https://bitzed.xyz/logo.png',
    description: 'Bitcoin spending app.',
  },
  {
    name: 'Aureo',
    network: NETWORK_LIGHTNING,
    url: 'https://app.aureobitcoin.com/',
    imgUrl: 'https://www.aureobitcoin.com/_next/image?url=https%3A%2F%2Fus-west-2.graphassets.com%2Fcmhi1xs950q2h06mx975ucw16%2Fcmhktrdr6kgdz07n1j9kz1fiz&w=3840&q=75',
    description: 'A Bitcoin on-ramp/off-ramp experience.',
  },
  {
    name: 'Offramp | Cashwyre',
    network: NETWORK_LIGHTNING,
    url: 'https://offramp.cashwyre.com/offramp',
    imgUrl: 'https://paylink-plugin.vercel.app/widget-icon.png',
    description: 'Cashwyre offramp for Bitcoin.',
  },
  {
    name: 'Use Tando',
    network: NETWORK_LIGHTNING,
    url: 'https://use.tando.me/',
    imgUrl: 'https://cdn.brandfetch.io/idpZe_Mbxi/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1749183223711',
    description: 'Spend Bitcoin anywhere in Kenya.',
  },
  {
    name: 'LNEsim',
    network: NETWORK_LIGHTNING,
    url: 'https://www.lnesim.com/',
    imgUrl: 'https://www.lnesim.com/lnesim.png',
    description: 'Instantly buy travel eSIM with Bitcoin Lightning Network',
  },
  {
    name: 'Bitrefill',
    network: NETWORK_BITCOIN,
    url: 'https://bitrefill.com',
    imgUrl: 'https://pbs.twimg.com/media/GgHHK5GWkAAp_6z.png',
    description: 'Buy gift cards with Bitcoin',
  },
  {
    name: 'Keystone',
    network: NETWORK_BITCOIN,
    url: 'https://bit.ly/3Q6Rz5m',
    imgUrl: 'https://pbs.twimg.com/profile_images/1787649407963574272/eHYwt7dk_400x400.jpg',
    description: 'Secure Cold Wallet for Effortless Transactions',
  },
  {
    name: 'Botanix Dapps',
    network: NETWORK_BOTANIX,
    url: 'https://botanixlabs.com/use',
    imgUrl: 'https://cdn.brandfetch.io/idEa3WW1c8/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1773848256724',
    description: 'Check out Botanix Dapps',
  },
  {
    name: 'Citrea Faucet',
    network: NETWORK_CITREA_TESTNET,
    url: 'https://citrea.xyz/faucet',
    imgUrl: '',
    description: '',
  },
  {
    name: 'Ecosystem',
    network: NETWORK_CITREA_TESTNET,
    url: 'https://citrea.xyz/ecosystem',
    imgUrl: '',
    description: '',
  },
  {
    name: 'Bridge',
    network: NETWORK_BOTANIX,
    url: 'https://bridge.botanixlabs.com',
    imgUrl: 'https://cdn.brandfetch.io/idEa3WW1c8/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1773848256724',
    description: 'Bridge Bitcoin to Botanix',
  },
  {
    name: 'Yield',
    network: NETWORK_BOTANIX,
    url: 'https://yield.botanixlabs.com/',
    imgUrl: 'https://cdn.brandfetch.io/idEa3WW1c8/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1773848256724',
    description: 'Bitcoin in - More Bitcoin out. Backed by economic activity',
  },
  {
    name: 'Oku Trade',
    network: NETWORK_ROOTSTOCK,
    url: 'https://oku.trade/?inputChain=rootstock',
    imgUrl: 'https://cdn.brandfetch.io/idKAuL9ClT/w/180/h/180/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1773398820981',
    description: 'The best routing options for Rootstock',
  },
  {
    name: 'Bridge',
    network: NETWORK_CITREA,
    url: 'https://citrea.xyz/bridge',
    imgUrl: 'https://cdn.brandfetch.io/idrgyTyq_W/w/180/h/180/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1769291838005',
    description: 'Bridge Bitcoin to Citrea',
  },
  {
    name: 'Citrea Dashboard',
    network: NETWORK_CITREA,
    url: 'https://app.citrea.xyz',
    imgUrl: 'https://cdn.brandfetch.io/idrgyTyq_W/w/180/h/180/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1769291838005',
    description: 'Your Citrea mainnet usage tiers, reflected in the progress bars.',
  },
  {
    name: 'Citrea Ecosystem',
    network: NETWORK_CITREA,
    url: 'https://citrea.xyz/ecosystem',
    imgUrl: 'https://cdn.brandfetch.io/idrgyTyq_W/w/180/h/180/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1769291838005',
    description: 'Built for Bitcoin, Powered by Citrea',
  },
  {
    name: 'Flashnet',
    network: NETWORK_SPARK,
    url: 'https://www.flashnet.xyz/',
    imgUrl: 'https://cdn.brandfetch.io/idCPksPrT0/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1770231197231',
    description: 'Fastest Bitcoin liquidity layer',
  },
  {
    name: 'UTXO.fun',
    network: NETWORK_SPARK,
    url: 'https://www.utxo.fun/',
    imgUrl: 'https://www.spark.money/ecosystem/app-utxo-fun.png',
    description: 'Bitcoin UTXO discovery',
  },
  {
    name: 'LendaSat',
    network: NETWORK_ARK,
    url: 'https://swap.lendasat.com/usdc_eth/btc_arkade',
    imgUrl: 'https://cdn.brandfetch.io/idiw3bB1RJ/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1760963964272',
    description: 'Bitcoin atomic swaps on Arkade.',
  },
];

export function getPartnersList(network: Networks): PartnerInfo[] {
  return partnersList.filter((dapp) => dapp.network === network);
}
